apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ex9-module-rds-cicd
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/cdmi4613/ex9-module-rds-cicd.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true