apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: company-backend

  template:
    metadata:
      labels:
        app: company-backend

    spec:
      serviceAccountName: company-backend

      containers:
        - name: backend

          image: 925047940866.dkr.ecr.ap-northeast-1.amazonaws.com/std01-ex9-backend:5ed1665f056bdcfc4e53891db0a405bb8c24cc8d

          ports:
            - containerPort: 8000

          env:
            - name: AWS_REGION
              value: "ap-northeast-1"

            - name: DB_HOST
                                                                      value: "std01-ex9-rds-proxy.proxy-c7k4iwowmk84.ap-northeast-1.rds.amazonaws.com"

            - name: DB_NAME
              value: "company"

            - name: DB_PORT
              value: "3306"

            - name: DB_SECRET_ARN
                                                                      value: "arn:aws:secretsmanager:ap-northeast-1:925047940866:secret:rds!db-dc1948ab-1bf3-4b4f-90d1-1dd800775dea-J4nV94"