apiVersion: apps/v1
kind: Deployment

metadata:
  name: company-frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: company-frontend

  template:
    metadata:
      labels:
        app: company-frontend

    spec:
      containers:
        - name: frontend
          image: 925047940866.dkr.ecr.ap-northeast-1.amazonaws.com/std01-ex9-frontend:d16e861203d64a17197a946b547152935db7abdd

          ports:
            - containerPort: 80