apiVersion: apps/v1
kind: Deployment

metadata:
  name: company-frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: company-frontend

  template:
    metadata:
      labels:
        app: company-frontend

    spec:
      containers:
        - name: frontend
          image: 925047940866.dkr.ecr.ap-northeast-1.amazonaws.com/std01-ex9-frontend:fbc9c2c50465b59fb552b62e30d64c2b5cb9cf96

          ports:
            - containerPort: 80