apiVersion: apps/v1
kind: Deployment

metadata:
  name: company-frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: company-frontend

  template:
    metadata:
      labels:
        app: company-frontend

    spec:
      containers:
        - name: frontend
          image: 925047940866.dkr.ecr.ap-northeast-1.amazonaws.com/std01-ex9-frontend:5ebae77b4bd0e3ad4ff159ad01fc3c3724431dab

          ports:
            - containerPort: 80